//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCategory
    {
        public int ID { get; set; }
        public int i_PID { get; set; }
        public string s_Name { get; set; }
        public string s_EnName { get; set; }
        public string s_ImgPath { get; set; }
        public bool b_IsRedirect { get; set; }
        public string s_RedirectUrl { get; set; }
        public bool b_IsShowNav { get; set; }
        public int i_TemplateID { get; set; }
        public bool b_IsContentItem { get; set; }
        public int i_ContentTemplateID { get; set; }
        public string s_Content { get; set; }
        public string s_ContentNoHtml { get; set; }
        public string s_GenarateRule { get; set; }
        public string s_ListGenarateRule { get; set; }
        public string s_KeyWord { get; set; }
        public string s_Description { get; set; }
        public int i_UserID { get; set; }
        public int i_Order { get; set; }
    }
}
