//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int ID { get; set; }
        public int i_CategoryID { get; set; }
        public string s_Title { get; set; }
        public string s_Author { get; set; }
        public string s_Summary { get; set; }
        public bool b_IsTop { get; set; }
        public bool b_IsSlide { get; set; }
        public bool b_IsHot { get; set; }
        public string s_ImgPath { get; set; }
        public string s_Content { get; set; }
        public string s_ContentNoHtml { get; set; }
        public string s_GenarateRule { get; set; }
        public string s_KeyWord { get; set; }
        public string s_Description { get; set; }
        public int i_TemplateID { get; set; }
        public string s_EnName { get; set; }
        public string s_AddTime { get; set; }
        public string s_UpdateTime { get; set; }
        public string s_Attach { get; set; }
        public string s_Size { get; set; }
        public string s_Lang { get; set; }
        public string s_Version { get; set; }
        public string s_PublishTime { get; set; }
        public int i_UserID { get; set; }
        public int i_Status { get; set; }
        public int i_ViewCount { get; set; }
    }
}
