//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int ID { get; set; }
        public string s_SoftName { get; set; }
        public string s_SoftSize { get; set; }
        public string s_SoftProvider { get; set; }
        public string s_SoftLang { get; set; }
        public string s_SoftVersion { get; set; }
        public string s_AppEnvironment { get; set; }
        public string s_UpdateTime { get; set; }
        public string s_SoftUrl { get; set; }
        public string s_SoftImgUrl { get; set; }
        public string s_SoftMemo { get; set; }
        public string s_SoftMemoNoHtml { get; set; }
        public int i_UserID { get; set; }
        public int i_Status { get; set; }
        public string s_AddTime { get; set; }
    }
}
