//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelItem_Value
    {
        public int ID { get; set; }
        public int i_TableID { get; set; }
        public string s_Content { get; set; }
        public string s_ContentNoHtml { get; set; }
        public int i_Order { get; set; }
        public string s_AddTime { get; set; }
    }
}
