//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public string s_UserName { get; set; }
        public string s_RealName { get; set; }
        public string s_Goods { get; set; }
        public string s_Phone { get; set; }
        public int i_Count { get; set; }
        public string s_Address { get; set; }
        public string s_OrderTime { get; set; }
        public string s_Message { get; set; }
    }
}
