//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string s_UserName { get; set; }
        public string s_Password { get; set; }
        public byte i_UserType { get; set; }
        public string s_RealName { get; set; }
        public string s_Phone { get; set; }
        public string s_Mail { get; set; }
        public byte i_Status { get; set; }
        public string s_Url { get; set; }
        public string s_Token { get; set; }
        public string s_AppId { get; set; }
        public string s_AppSecret { get; set; }
        public string s_WeixinAccount { get; set; }
        public string s_WeixinID { get; set; }
    }
}
