//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebConfig
    {
        public int ID { get; set; }
        public string s_SiteName { get; set; }
        public string s_SiteDNS { get; set; }
        public string s_CopyRight { get; set; }
        public string s_Filing { get; set; }
        public string s_KeyWord { get; set; }
        public string s_Description { get; set; }
        public string s_Email { get; set; }
        public string s_Phone { get; set; }
        public string s_Address { get; set; }
        public int i_PageSize { get; set; }
    }
}
